services:
    app:
        container_name: collabsphere-app
        image: nghtai/collapsphere_v1:latest
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "${APP_HTTP_PORT}:80"
            - "${APP_HTTPS_PORT}:443"
        environment:
            - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT}
            - Database__ConnectionString=${DATABASE_CONNECTION_STRING}
            - ASPNETCORE_URLS=${ASPNETCORE_URLS}
            - ASPNETCORE_SWAGGER_ENABLED=${ASPNETCORE_SWAGGER_ENABLED}
              # Vô hiệu hóa cấu hình HTTPS vì chứng chỉ chưa được tạo
              # - ASPNETCORE_HTTPS_PORT=8081
              # - ASPNETCORE_Kestrel__Certificates__Default__Password=collabsphere
              # - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
        depends_on:
            db:
                condition: service_healthy
        command: ["/wait-for-mysql.sh", "db", "dotnet", "CollabSphere.dll"]
        networks:
            - collabsphere-network
        volumes:
            - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
            - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro

    db:
        image: mysql:8.0
        container_name: collabsphere-mysql
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: collabsphere
            MYSQL_DATABASE: collabsphere
        ports:
            - "3333:3306"
        volumes:
            - mysql-data:/var/lib/mysql
        networks:
            - collabsphere-network
        command: --default-authentication-plugin=mysql_native_password
        healthcheck:
            test:
                [
                    "CMD",
                    "mysqladmin",
                    "ping",
                    "-h",
                    "localhost",
                    "-u",
                    "root",
                    "-pcollabsphere",
                ]
            interval: 5s
            timeout: 5s
            retries: 5
            start_period: 30s

networks:
    collabsphere-network:
        driver: bridge

volumes:
    mysql-data:
